version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    container_name: app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
      - redis
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp_development
    stdin_open: true
    tty: true

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  postgres_data:
