databases:
  - name: Wordlog.db 
    databaseName: wordlog_db_86lb  
    user: wordlog  
    region: singapore

services:
  - type: web
    name: wordlog 
    env: ruby
    region: singapore
    plan: starter 
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Wordlog.db 
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false


